import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import CoinList from '../components/CoinList'
import Coins from '../components/Coins/Coins'
import Footer from '../components/Footer/Footer'
import Layout from '../components/Layout'
import SearchBar from '../components/SearchBar/SearchBar'


export default function Home({filteredCoins}) {
  // console.log(filteredCoins);

  const [search, setSearch] = useState('');

  const allCoins = filteredCoins.filter(coin =>
    coin.name.toLowerCase().includes(search.toLowerCase())
  );
// searching in search bar

  const handleChange = e => {
    e.preventDefault();

    setSearch(e.target.value.toLowerCase());
  };
  // seting the value to target which we have entered 

  return (
    <>
    <Layout>
      {/* <Head>
        <title>Crypto-Finance-Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className="coin_app">
          <SearchBar type="text" placeholder="search" onChange={handleChange}/>
          <CoinList filteredCoins={allCoins}/>
      </div>
       
    </Layout>
    <Footer />  
    </>
  )
}


export const getServerSideProps = async () => {
  const res = await fetch("https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&order=market_cap_desc&per_page=20&page=1&sparkline=false");
  
  const filteredCoins = await res.json();

  return {
    props: {
      filteredCoins
    }
  };
}